/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Main;

import DataBase.Connect;
import java.awt.HeadlessException;
import java.awt.Image;
import java.sql.Connection;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.sql.Statement;
import javax.swing.ImageIcon;
import javax.swing.JOptionPane;

/**
 *
 * @author YLVVST
 */
public class MainUI extends javax.swing.JFrame
{

    int contador = 1;
    int[] indice = new int[12];
    int answers = 0;
    String[] respuesta = new String[12];
    private String sexo, nombre, edad, puntaje, resultado;
    Connect cc = new Connect();
    Connection cn = cc.connect();

    public MainUI()
    {
        initComponents();
        Image imagen = new ImageIcon(getClass().getResource("/Resources/app_logo.png")).getImage();
        this.setIconImage(imagen);
        this.setLocationRelativeTo(null);
        this.jLabelLogoGIF.setVisible(false);
        this.jLabelLogoWaiting.setVisible(false);
        this.jButtonPlay.setVisible(false);
        this.jButtonFinalizar.setVisible(false);
        stateLayoutQuestion(false);
    }

    public void mostrarPregunta()
    {
        String sql;
        int valor;
        valor = contador;
        sql = "SELECT Pregunta FROM ExamenEstres WHERE id='" + valor + "'";
        try
        {
            Statement st = cn.createStatement();
            ResultSet rs = st.executeQuery(sql);
            if (rs.next())
            {
                jTextPanePregunta.setText(String.valueOf(contador + ".- ¿" + rs.getString("pregunta")));
                if (contador > 11)
                {
                    this.jButtonFinalizar.setVisible(true);
                    this.jButtonSiguiente.setEnabled(false);
                }
                else
                {
                    this.jButtonFinalizar.setVisible(false);
                    this.jButtonSiguiente.setEnabled(true);
                }
            }
        }
        catch (SQLException ex)
        {
            JOptionPane.showMessageDialog(null, "No se realizó la conexión con éxito.", "ERROR FATAL", 0);
        }
    }

    public void stateLayoutUser(boolean state)
    {
        this.jLabelUser.setVisible(state);
        this.jTextFieldNombre.setVisible(state);
        this.jTextFieldEdad.setVisible(state);
        this.jComboBoxSexo.setVisible(state);
        this.jButtonBorrarCampos.setVisible(state);
        this.jButtonNuevoAspirante.setVisible(state);
        this.jButtonConsultar.setVisible(state);
        this.jLabelRegistro.setVisible(state);
        this.jLabelLogo.setVisible(state);
    }

    public void stateLayoutQuestion(boolean state)
    {
        this.jRadioButton1.setVisible(state);
        this.jRadioButton2.setVisible(state);
        this.jRadioButton3.setVisible(state);
        this.jRadioButton4.setVisible(state);
        this.jRadioButton5.setVisible(state);
        this.jRadioButton6.setVisible(state);
        this.jButtonAnterior.setVisible(state);
        this.jButtonSiguiente.setVisible(state);
        this.jButtonFinalizar.setVisible(state);
        this.jLabelLogoGIF.setVisible(state);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents()
    {

        buttonGroup1 = new javax.swing.ButtonGroup();
        jButtonClose = new javax.swing.JButton();
        jButtonMinimize = new javax.swing.JButton();
        jLabelLogo = new javax.swing.JLabel();
        jTextFieldEdad = new javax.swing.JTextField();
        jTextFieldNombre = new javax.swing.JTextField();
        jComboBoxSexo = new javax.swing.JComboBox<>();
        jLabelUser = new javax.swing.JLabel();
        jButtonBorrarCampos = new javax.swing.JButton();
        jButtonConsultar = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTextPanePregunta = new javax.swing.JTextPane();
        jRadioButton1 = new javax.swing.JRadioButton();
        jRadioButton2 = new javax.swing.JRadioButton();
        jRadioButton3 = new javax.swing.JRadioButton();
        jRadioButton4 = new javax.swing.JRadioButton();
        jRadioButton5 = new javax.swing.JRadioButton();
        jRadioButton6 = new javax.swing.JRadioButton();
        jButtonSiguiente = new javax.swing.JButton();
        jButtonAnterior = new javax.swing.JButton();
        jButtonFinalizar = new javax.swing.JButton();
        jLabelQuestion = new javax.swing.JLabel();
        jButtonNuevoAspirante = new javax.swing.JButton();
        jButtonPlay = new javax.swing.JButton();
        jLabelLogoWaiting = new javax.swing.JLabel();
        jLabelLogoGIF = new javax.swing.JLabel();
        jLabelRegistro = new javax.swing.JLabel();
        jLabelWallpaper = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setUndecorated(true);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jButtonClose.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Resources/close.png"))); // NOI18N
        jButtonClose.setToolTipText("Cerrar");
        jButtonClose.setBorderPainted(false);
        jButtonClose.setContentAreaFilled(false);
        jButtonClose.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jButtonClose.setFocusPainted(false);
        jButtonClose.addActionListener(new java.awt.event.ActionListener()
        {
            public void actionPerformed(java.awt.event.ActionEvent evt)
            {
                jButtonCloseActionPerformed(evt);
            }
        });
        getContentPane().add(jButtonClose, new org.netbeans.lib.awtextra.AbsoluteConstraints(1320, 10, 40, 40));

        jButtonMinimize.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Resources/minimize.png"))); // NOI18N
        jButtonMinimize.setToolTipText("Minimizar");
        jButtonMinimize.setBorderPainted(false);
        jButtonMinimize.setContentAreaFilled(false);
        jButtonMinimize.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jButtonMinimize.setFocusPainted(false);
        jButtonMinimize.addActionListener(new java.awt.event.ActionListener()
        {
            public void actionPerformed(java.awt.event.ActionEvent evt)
            {
                jButtonMinimizeActionPerformed(evt);
            }
        });
        getContentPane().add(jButtonMinimize, new org.netbeans.lib.awtextra.AbsoluteConstraints(1270, 10, 40, 40));

        jLabelLogo.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabelLogo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Resources/main_isologo.png"))); // NOI18N
        getContentPane().add(jLabelLogo, new org.netbeans.lib.awtextra.AbsoluteConstraints(650, 90, 620, 210));

        jTextFieldEdad.setFont(new java.awt.Font("Futura Lt BT", 0, 30)); // NOI18N
        jTextFieldEdad.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        jTextFieldEdad.setBorder(null);
        jTextFieldEdad.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        getContentPane().add(jTextFieldEdad, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 350, 70, 40));

        jTextFieldNombre.setFont(new java.awt.Font("Futura Lt BT", 0, 30)); // NOI18N
        jTextFieldNombre.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        jTextFieldNombre.setBorder(null);
        jTextFieldNombre.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        getContentPane().add(jTextFieldNombre, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 280, 310, 40));

        jComboBoxSexo.setFont(new java.awt.Font("Futura Lt BT", 0, 30)); // NOI18N
        jComboBoxSexo.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { " ", "Femenino", "Masculino" }));
        getContentPane().add(jComboBoxSexo, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 420, -1, 40));

        jLabelUser.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Resources/label_user.png"))); // NOI18N
        getContentPane().add(jLabelUser, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 190, -1, -1));

        jButtonBorrarCampos.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Resources/delete_button.png"))); // NOI18N
        jButtonBorrarCampos.setToolTipText("Borrar Campos");
        jButtonBorrarCampos.setBorderPainted(false);
        jButtonBorrarCampos.setContentAreaFilled(false);
        jButtonBorrarCampos.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jButtonBorrarCampos.setFocusable(false);
        jButtonBorrarCampos.addActionListener(new java.awt.event.ActionListener()
        {
            public void actionPerformed(java.awt.event.ActionEvent evt)
            {
                jButtonBorrarCamposActionPerformed(evt);
            }
        });
        getContentPane().add(jButtonBorrarCampos, new org.netbeans.lib.awtextra.AbsoluteConstraints(400, 550, 80, 80));

        jButtonConsultar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Resources/query_button.png"))); // NOI18N
        jButtonConsultar.setToolTipText("Consultar Resultados");
        jButtonConsultar.setBorderPainted(false);
        jButtonConsultar.setContentAreaFilled(false);
        jButtonConsultar.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jButtonConsultar.setFocusPainted(false);
        jButtonConsultar.setFocusable(false);
        jButtonConsultar.addActionListener(new java.awt.event.ActionListener()
        {
            public void actionPerformed(java.awt.event.ActionEvent evt)
            {
                jButtonConsultarActionPerformed(evt);
            }
        });
        getContentPane().add(jButtonConsultar, new org.netbeans.lib.awtextra.AbsoluteConstraints(870, 420, 170, 160));

        jTextPanePregunta.setEditable(false);
        jTextPanePregunta.setBackground(new java.awt.Color(51, 51, 51));
        jTextPanePregunta.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        jTextPanePregunta.setFont(new java.awt.Font("Futura Hv BT", 0, 36)); // NOI18N
        jTextPanePregunta.setForeground(new java.awt.Color(51, 51, 51));
        jTextPanePregunta.setAutoscrolls(false);
        jTextPanePregunta.setFocusable(false);
        jTextPanePregunta.setOpaque(false);
        jScrollPane1.setViewportView(jTextPanePregunta);

        getContentPane().add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(650, 90, 620, 210));

        buttonGroup1.add(jRadioButton1);
        jRadioButton1.setFont(new java.awt.Font("Futura Lt BT", 0, 40)); // NOI18N
        jRadioButton1.setText("Nunca");
        jRadioButton1.setContentAreaFilled(false);
        jRadioButton1.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jRadioButton1.setIconTextGap(10);
        jRadioButton1.addActionListener(new java.awt.event.ActionListener()
        {
            public void actionPerformed(java.awt.event.ActionEvent evt)
            {
                jRadioButton1ActionPerformed(evt);
            }
        });
        getContentPane().add(jRadioButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(770, 400, 380, -1));

        buttonGroup1.add(jRadioButton2);
        jRadioButton2.setFont(new java.awt.Font("Futura Lt BT", 0, 40)); // NOI18N
        jRadioButton2.setText("Casi nunca");
        jRadioButton2.setContentAreaFilled(false);
        jRadioButton2.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jRadioButton2.setIconTextGap(10);
        getContentPane().add(jRadioButton2, new org.netbeans.lib.awtextra.AbsoluteConstraints(770, 440, 380, -1));

        buttonGroup1.add(jRadioButton3);
        jRadioButton3.setFont(new java.awt.Font("Futura Lt BT", 0, 40)); // NOI18N
        jRadioButton3.setText("Pocas veces");
        jRadioButton3.setContentAreaFilled(false);
        jRadioButton3.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jRadioButton3.setIconTextGap(10);
        getContentPane().add(jRadioButton3, new org.netbeans.lib.awtextra.AbsoluteConstraints(770, 480, 380, -1));

        buttonGroup1.add(jRadioButton4);
        jRadioButton4.setFont(new java.awt.Font("Futura Lt BT", 0, 40)); // NOI18N
        jRadioButton4.setText("Algunas veces");
        jRadioButton4.setContentAreaFilled(false);
        jRadioButton4.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jRadioButton4.setIconTextGap(10);
        getContentPane().add(jRadioButton4, new org.netbeans.lib.awtextra.AbsoluteConstraints(770, 520, 380, -1));

        buttonGroup1.add(jRadioButton5);
        jRadioButton5.setFont(new java.awt.Font("Futura Lt BT", 0, 40)); // NOI18N
        jRadioButton5.setText("Frecuentemente");
        jRadioButton5.setContentAreaFilled(false);
        jRadioButton5.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jRadioButton5.setIconTextGap(10);
        getContentPane().add(jRadioButton5, new org.netbeans.lib.awtextra.AbsoluteConstraints(770, 560, 380, -1));

        buttonGroup1.add(jRadioButton6);
        jRadioButton6.setFont(new java.awt.Font("Futura Lt BT", 0, 40)); // NOI18N
        jRadioButton6.setText("Muy frecuentemente");
        jRadioButton6.setContentAreaFilled(false);
        jRadioButton6.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jRadioButton6.setIconTextGap(10);
        getContentPane().add(jRadioButton6, new org.netbeans.lib.awtextra.AbsoluteConstraints(770, 600, 380, -1));

        jButtonSiguiente.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Resources/next_button.png"))); // NOI18N
        jButtonSiguiente.setToolTipText("Siguiente");
        jButtonSiguiente.setBorderPainted(false);
        jButtonSiguiente.setContentAreaFilled(false);
        jButtonSiguiente.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jButtonSiguiente.setFocusPainted(false);
        jButtonSiguiente.setFocusable(false);
        jButtonSiguiente.addActionListener(new java.awt.event.ActionListener()
        {
            public void actionPerformed(java.awt.event.ActionEvent evt)
            {
                jButtonSiguienteActionPerformed(evt);
            }
        });
        getContentPane().add(jButtonSiguiente, new org.netbeans.lib.awtextra.AbsoluteConstraints(1190, 320, 80, 80));

        jButtonAnterior.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Resources/prev_button.png"))); // NOI18N
        jButtonAnterior.setToolTipText("Anterior");
        jButtonAnterior.setBorderPainted(false);
        jButtonAnterior.setContentAreaFilled(false);
        jButtonAnterior.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jButtonAnterior.setFocusPainted(false);
        jButtonAnterior.setFocusable(false);
        jButtonAnterior.addActionListener(new java.awt.event.ActionListener()
        {
            public void actionPerformed(java.awt.event.ActionEvent evt)
            {
                jButtonAnteriorActionPerformed(evt);
            }
        });
        getContentPane().add(jButtonAnterior, new org.netbeans.lib.awtextra.AbsoluteConstraints(650, 320, 80, 80));

        jButtonFinalizar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Resources/end_button.png"))); // NOI18N
        jButtonFinalizar.setToolTipText("Finalizar Encuesta");
        jButtonFinalizar.setBorderPainted(false);
        jButtonFinalizar.setContentAreaFilled(false);
        jButtonFinalizar.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jButtonFinalizar.setFocusPainted(false);
        jButtonFinalizar.addActionListener(new java.awt.event.ActionListener()
        {
            public void actionPerformed(java.awt.event.ActionEvent evt)
            {
                jButtonFinalizarActionPerformed(evt);
            }
        });
        getContentPane().add(jButtonFinalizar, new org.netbeans.lib.awtextra.AbsoluteConstraints(920, 320, 80, -1));

        jLabelQuestion.setBackground(new java.awt.Color(0, 0, 0));
        jLabelQuestion.setForeground(new java.awt.Color(0, 0, 0));
        jLabelQuestion.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Resources/label_question.png"))); // NOI18N
        getContentPane().add(jLabelQuestion, new org.netbeans.lib.awtextra.AbsoluteConstraints(610, 70, -1, -1));

        jButtonNuevoAspirante.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Resources/new_user.png"))); // NOI18N
        jButtonNuevoAspirante.setToolTipText("Agregar Aspirante");
        jButtonNuevoAspirante.setBorderPainted(false);
        jButtonNuevoAspirante.setContentAreaFilled(false);
        jButtonNuevoAspirante.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jButtonNuevoAspirante.setFocusPainted(false);
        jButtonNuevoAspirante.setFocusable(false);
        jButtonNuevoAspirante.addActionListener(new java.awt.event.ActionListener()
        {
            public void actionPerformed(java.awt.event.ActionEvent evt)
            {
                jButtonNuevoAspiranteActionPerformed(evt);
            }
        });
        getContentPane().add(jButtonNuevoAspirante, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 550, 80, 80));

        jButtonPlay.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Resources/play_button.png"))); // NOI18N
        jButtonPlay.setToolTipText("Empezar Test");
        jButtonPlay.setBorderPainted(false);
        jButtonPlay.setContentAreaFilled(false);
        jButtonPlay.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jButtonPlay.setFocusPainted(false);
        jButtonPlay.setFocusable(false);
        jButtonPlay.addActionListener(new java.awt.event.ActionListener()
        {
            public void actionPerformed(java.awt.event.ActionEvent evt)
            {
                jButtonPlayActionPerformed(evt);
            }
        });
        getContentPane().add(jButtonPlay, new org.netbeans.lib.awtextra.AbsoluteConstraints(250, 520, 100, 80));

        jLabelLogoWaiting.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabelLogoWaiting.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Resources/logo_waiting.gif"))); // NOI18N
        getContentPane().add(jLabelLogoWaiting, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 110, 480, 440));

        jLabelLogoGIF.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Resources/logo_loading.gif"))); // NOI18N
        getContentPane().add(jLabelLogoGIF, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 70, -1, 610));

        jLabelRegistro.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabelRegistro.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Resources/label_title.png"))); // NOI18N
        getContentPane().add(jLabelRegistro, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 100, 480, -1));

        jLabelWallpaper.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabelWallpaper.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Resources/wallpaper.png"))); // NOI18N
        getContentPane().add(jLabelWallpaper, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, -1));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButtonCloseActionPerformed(java.awt.event.ActionEvent evt)//GEN-FIRST:event_jButtonCloseActionPerformed
    {//GEN-HEADEREND:event_jButtonCloseActionPerformed
        System.exit(0);
    }//GEN-LAST:event_jButtonCloseActionPerformed

    private void jButtonMinimizeActionPerformed(java.awt.event.ActionEvent evt)//GEN-FIRST:event_jButtonMinimizeActionPerformed
    {//GEN-HEADEREND:event_jButtonMinimizeActionPerformed
        this.setExtendedState(ICONIFIED);
    }//GEN-LAST:event_jButtonMinimizeActionPerformed

    private void jButtonNuevoAspiranteActionPerformed(java.awt.event.ActionEvent evt)//GEN-FIRST:event_jButtonNuevoAspiranteActionPerformed
    {//GEN-HEADEREND:event_jButtonNuevoAspiranteActionPerformed
        try
        {
            Integer.parseInt(jTextFieldEdad.getText());
        }
        catch (NumberFormatException e)
        {
            JOptionPane.showMessageDialog(null, "ERROR: Ingrese una edad válida");
            jTextFieldEdad.requestFocus();
            jTextFieldEdad.selectAll();
        }
                
        if (jTextFieldNombre.getText().equals("") || !jTextFieldNombre.getText().matches("^[a-z A-ZÑñÁáÉéÍíÓóÚú']+$"))
        {
            JOptionPane.showMessageDialog(null, "ERROR: Ingrese un nombre válido");
            jTextFieldNombre.requestFocus();
            jTextFieldNombre.selectAll();
        }
        
        else if (jTextFieldEdad.getText().equals("") || Integer.valueOf(jTextFieldEdad.getText()) <= 5
                || Integer.valueOf(jTextFieldEdad.getText()) >= 95)
        {
            JOptionPane.showMessageDialog(null, "ERROR: Ingrese una edad válida");
            jTextFieldEdad.requestFocus();
            jTextFieldEdad.selectAll();
        }

        else if (jComboBoxSexo.getSelectedIndex() == 0)
        {
            JOptionPane.showMessageDialog(null, "ERROR: Seleccione un sexo");
            jComboBoxSexo.requestFocus();
            jComboBoxSexo.showPopup();
        }

        else
        {
            try
            {
                PreparedStatement pst = cn.prepareStatement("INSERT INTO Personas(nombre, edad, sexo, puntaje, diagnostico) VALUES (?,?,?,?,?)");
                pst.setString(1, jTextFieldNombre.getText());
                pst.setString(2, jTextFieldEdad.getText());
                pst.setString(3, String.valueOf(jComboBoxSexo.getSelectedItem()));
                pst.setString(4, String.valueOf(getTotal()));
                pst.setString(5, getDiagnostico());
                pst.executeUpdate();
            }
            catch (HeadlessException | SQLException e)
            {
                System.out.print(e.getMessage());
            }

            JOptionPane.showMessageDialog(null, "Aspirante registrado");
            stateLayoutUser(false);
            this.jLabelLogo.setVisible(false);
            this.jLabelLogoWaiting.setVisible(true);
            this.jButtonPlay.setVisible(true);
            nombre = jTextFieldNombre.getText();
            edad = jTextFieldEdad.getText();
            sexo = String.valueOf(jComboBoxSexo.getSelectedItem());
        }
    }//GEN-LAST:event_jButtonNuevoAspiranteActionPerformed

    private void jButtonPlayActionPerformed(java.awt.event.ActionEvent evt)//GEN-FIRST:event_jButtonPlayActionPerformed
    {//GEN-HEADEREND:event_jButtonPlayActionPerformed
        this.jLabelLogoGIF.setVisible(true);
        this.jLabelLogoWaiting.setVisible(false);
        this.jButtonPlay.setVisible(false);
        stateLayoutQuestion(true);
        mostrarPregunta();
    }//GEN-LAST:event_jButtonPlayActionPerformed

    private void jButtonAnteriorActionPerformed(java.awt.event.ActionEvent evt)//GEN-FIRST:event_jButtonAnteriorActionPerformed
    {//GEN-HEADEREND:event_jButtonAnteriorActionPerformed
        if (contador > 1)
        {
            if (jRadioButton1.isSelected())
            {
                indice[contador - 1] = 1;
                respuesta[contador - 1] = jRadioButton1.getText();
                contador--;
                mostrarPregunta();
            }
            else if (jRadioButton2.isSelected())
            {
                indice[contador - 1] = 2;
                respuesta[contador - 1] = jRadioButton2.getText();
                contador--;
                mostrarPregunta();
            }
            else if (jRadioButton3.isSelected())
            {
                indice[contador - 1] = 3;
                respuesta[contador - 1] = jRadioButton3.getText();
                contador--;
                mostrarPregunta();

            }
            else if (jRadioButton4.isSelected())
            {
                indice[contador - 1] = 4;
                respuesta[contador - 1] = jRadioButton4.getText();
                contador--;
                mostrarPregunta();
            }
            else if (jRadioButton5.isSelected())
            {
                indice[contador - 1] = 5;
                respuesta[contador - 1] = jRadioButton5.getText();
                contador--;
                mostrarPregunta();
            }
            else if (jRadioButton6.isSelected())
            {
                indice[contador - 1] = 6;
                respuesta[contador - 1] = jRadioButton6.getText();
                contador--;
                mostrarPregunta();
            }
            else
            {
                JOptionPane.showMessageDialog(null, "Responda la pregunta.", "", 0);
            }
        }
    }//GEN-LAST:event_jButtonAnteriorActionPerformed

    private void jButtonSiguienteActionPerformed(java.awt.event.ActionEvent evt)//GEN-FIRST:event_jButtonSiguienteActionPerformed
    {//GEN-HEADEREND:event_jButtonSiguienteActionPerformed
        if (contador <= indice.length)
        {
            if (jRadioButton1.isSelected())
            {
                indice[contador - 1] = 1;
                respuesta[contador - 1] = jRadioButton1.getText();
                contador++;
                mostrarPregunta();
            }
            else if (jRadioButton2.isSelected())
            {
                indice[contador - 1] = 2;
                respuesta[contador - 1] = jRadioButton2.getText();
                contador++;
                mostrarPregunta();
            }
            else if (jRadioButton3.isSelected())
            {
                indice[contador - 1] = 3;
                respuesta[contador - 1] = jRadioButton3.getText();
                contador++;
                mostrarPregunta();
            }
            else if (jRadioButton4.isSelected())
            {
                indice[contador - 1] = 4;
                respuesta[contador - 1] = jRadioButton4.getText();
                contador++;
                mostrarPregunta();
            }
            else if (jRadioButton5.isSelected())
            {
                indice[contador - 1] = 5;
                respuesta[contador - 1] = jRadioButton5.getText();
                contador++;
                mostrarPregunta();
            }
            else if (jRadioButton6.isSelected())
            {
                indice[contador - 1] = 6;
                respuesta[contador - 1] = jRadioButton6.getText();
                contador++;
                mostrarPregunta();
            }
            else
            {
                JOptionPane.showMessageDialog(null, "Responda la pregunta.", "", 0);
            }
        }
    }//GEN-LAST:event_jButtonSiguienteActionPerformed

    private void jButtonFinalizarActionPerformed(java.awt.event.ActionEvent evt)//GEN-FIRST:event_jButtonFinalizarActionPerformed
    {//GEN-HEADEREND:event_jButtonFinalizarActionPerformed
        if (contador <= indice.length)
        {
            if (jRadioButton1.isSelected())
            {
                indice[contador - 1] = 1;
                respuesta[contador - 1] = jRadioButton1.getText();
                contador++;
                mostrarPregunta();
            }
            else if (jRadioButton2.isSelected())
            {
                indice[contador - 1] = 2;
                respuesta[contador - 1] = jRadioButton2.getText();
                contador++;
                mostrarPregunta();
            }
            else if (jRadioButton3.isSelected())
            {
                indice[contador - 1] = 3;
                respuesta[contador - 1] = jRadioButton3.getText();
                contador++;
                mostrarPregunta();
            }
            else if (jRadioButton4.isSelected())
            {
                indice[contador - 1] = 4;
                respuesta[contador - 1] = jRadioButton4.getText();
                contador++;
                mostrarPregunta();
            }
            else if (jRadioButton5.isSelected())
            {
                indice[contador - 1] = 5;
                respuesta[contador - 1] = jRadioButton5.getText();
                contador++;
                mostrarPregunta();
            }
            else if (jRadioButton6.isSelected())
            {
                indice[contador - 1] = 6;
                respuesta[contador - 1] = jRadioButton6.getText();
                contador++;
                mostrarPregunta();
            }
            else
            {
                JOptionPane.showMessageDialog(null, "Responda la pregunta.", "", 0);
            }
        }

        try
        {
            PreparedStatement pst = cn.prepareStatement("INSERT INTO Respuestas(Pregunta1, Pregunta2, Pregunta3, Pregunta4, Pregunta5, Pregunta6, Pregunta7, Pregunta8, Pregunta9, Pregunta10, Pregunta11, Pregunta12) VALUES (?,?,?,?,?,?,?,?,?,?,?,?)");
            pst.setString(1, respuesta[0]);
            pst.setString(2, respuesta[1]);
            pst.setString(3, respuesta[2]);
            pst.setString(4, respuesta[3]);
            pst.setString(5, respuesta[4]);
            pst.setString(6, respuesta[5]);
            pst.setString(7, respuesta[6]);
            pst.setString(8, respuesta[7]);
            pst.setString(9, respuesta[8]);
            pst.setString(10, respuesta[9]);
            pst.setString(11, respuesta[10]);
            pst.setString(12, respuesta[11]);
            pst.executeUpdate();
            JOptionPane.showMessageDialog(null, "Respuestas de aspirante guardadas exitosamente.", "Registro Correcto", 1);
            stateLayoutUser(true);
            stateLayoutQuestion(false);
        }
        catch (HeadlessException | SQLException e)
        {
            System.out.print(e.getMessage());
        }
        try
        {
            PreparedStatement pst = cn.prepareStatement("UPDATE Personas SET Personas.Nombre=?,Edad=?,Sexo=?,"
                    + "Puntaje=?,Diagnostico=? WHERE Personas.Id = (SELECT MAX([Id]) FROM Personas)");
            pst.setString(1, jTextFieldNombre.getText());
            pst.setString(2, jTextFieldEdad.getText());
            pst.setString(3, String.valueOf(jComboBoxSexo.getSelectedItem()));
            pst.setString(4, String.valueOf(getTotal()));
            pst.setString(5, getDiagnostico());
            pst.executeUpdate();
            
             jTextPanePregunta.setText(" ");
            
            contador = 1;
            indice = new int[12];
            answers = 0;
            respuesta = new String[12];
        }
        catch (HeadlessException | SQLException e)
        {
            System.out.print(e.getMessage());
        }
    }//GEN-LAST:event_jButtonFinalizarActionPerformed

    private void jButtonConsultarActionPerformed(java.awt.event.ActionEvent evt)//GEN-FIRST:event_jButtonConsultarActionPerformed
    {//GEN-HEADEREND:event_jButtonConsultarActionPerformed
        QueryUI window = new QueryUI();
        this.dispose();
        window.setVisible(true);
    }//GEN-LAST:event_jButtonConsultarActionPerformed

    private void jRadioButton1ActionPerformed(java.awt.event.ActionEvent evt)//GEN-FIRST:event_jRadioButton1ActionPerformed
    {//GEN-HEADEREND:event_jRadioButton1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jRadioButton1ActionPerformed

    private void jButtonBorrarCamposActionPerformed(java.awt.event.ActionEvent evt)//GEN-FIRST:event_jButtonBorrarCamposActionPerformed
    {//GEN-HEADEREND:event_jButtonBorrarCamposActionPerformed
        jTextFieldNombre.setText(" ");
        jTextFieldEdad.setText(" ");
        jComboBoxSexo.setSelectedIndex(0);
    }//GEN-LAST:event_jButtonBorrarCamposActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[])
    {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try
        {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels())
            {
                if ("Nimbus".equals(info.getName()))
                {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;

                }
            }
        }
        catch (ClassNotFoundException ex)
        {
            java.util.logging.Logger.getLogger(MainUI.class
                    .getName()).log(java.util.logging.Level.SEVERE, null, ex);

        }
        catch (InstantiationException ex)
        {
            java.util.logging.Logger.getLogger(MainUI.class
                    .getName()).log(java.util.logging.Level.SEVERE, null, ex);

        }
        catch (IllegalAccessException ex)
        {
            java.util.logging.Logger.getLogger(MainUI.class
                    .getName()).log(java.util.logging.Level.SEVERE, null, ex);

        }
        catch (javax.swing.UnsupportedLookAndFeelException ex)
        {
            java.util.logging.Logger.getLogger(MainUI.class
                    .getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable()
        {
            public void run()
            {
                new MainUI().setVisible(true);
            }
        });
    }

    public int getTotal()
    {
        int total = 0;
        for (int i = 0; i < indice.length; i++)
        {
            total = total + indice[i];
        }
        return total;
    }

    public String getDiagnostico()
    {
        String resultado1;
        if (getTotal() >= 0 && getTotal() <= 30)
        {
            resultado1 = "No estrés";
        }
        else if (getTotal() >= 31 && getTotal() <= 42)
        {
            resultado1 = "Estrés leve";
        }
        else if (getTotal() >= 43 && getTotal() <= 54)
        {
            resultado1 = "Estrés medio";
        }
        else if (getTotal() >= 55 && getTotal() <= 66)
        {
            resultado1 = "Estrés alto";
        }
        else if (getTotal() >= 67 && getTotal() <= 72)
        {
            resultado1 = "Estres grave";
        }
        else
        {
            resultado1 = "Estrés fuera de rango";
        }

        return resultado1;
    }

    public String getSexo()
    {
        sexo = String.valueOf(jComboBoxSexo.getSelectedItem());
        return sexo;
    }

    public String getEdad()
    {
        edad = jTextFieldEdad.getText();
        return edad;
    }

    public String getNombre()
    {
        nombre = jTextFieldNombre.getText();
        return nombre;
    }

    public String getPuntaje()
    {
        puntaje = String.valueOf(getTotal());
        return puntaje;
    }

    public String getResultado()
    {
        resultado = getDiagnostico();
        return resultado;
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.ButtonGroup buttonGroup1;
    private javax.swing.JButton jButtonAnterior;
    private javax.swing.JButton jButtonBorrarCampos;
    private javax.swing.JButton jButtonClose;
    private javax.swing.JButton jButtonConsultar;
    private javax.swing.JButton jButtonFinalizar;
    private javax.swing.JButton jButtonMinimize;
    private javax.swing.JButton jButtonNuevoAspirante;
    private javax.swing.JButton jButtonPlay;
    private javax.swing.JButton jButtonSiguiente;
    private javax.swing.JComboBox<String> jComboBoxSexo;
    private javax.swing.JLabel jLabelLogo;
    private javax.swing.JLabel jLabelLogoGIF;
    private javax.swing.JLabel jLabelLogoWaiting;
    private javax.swing.JLabel jLabelQuestion;
    private javax.swing.JLabel jLabelRegistro;
    private javax.swing.JLabel jLabelUser;
    private javax.swing.JLabel jLabelWallpaper;
    private javax.swing.JRadioButton jRadioButton1;
    private javax.swing.JRadioButton jRadioButton2;
    private javax.swing.JRadioButton jRadioButton3;
    private javax.swing.JRadioButton jRadioButton4;
    private javax.swing.JRadioButton jRadioButton5;
    private javax.swing.JRadioButton jRadioButton6;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTextField jTextFieldEdad;
    private javax.swing.JTextField jTextFieldNombre;
    private javax.swing.JTextPane jTextPanePregunta;
    // End of variables declaration//GEN-END:variables
}
