package Default;

import java.awt.BorderLayout;
import java.awt.Color;
import java.awt.Graphics;
import javax.swing.ImageIcon;
import DataBase.Connect;

/**
 *
 * @author YLVVST
 */
public class Splash extends javax.swing.JPanel
{

    ImageIcon image;
    BorderLayout scheme;

    public Splash()
    {
        initComponents();
        state.setForeground(Color.gray);
        setBackground(new Color(0, 255, 0, 0));
        image = new ImageIcon(getClass().getResource("/Resources/splash.png"));
        this.setSize(image.getIconWidth(), image.getIconHeight());
    }

    @Override
    public void paintComponent(Graphics g)
    {
        super.paintComponent(g);
        g.drawImage(image.getImage(), 0, 0, image.getIconWidth(), image.getIconHeight(), this);
        this.setOpaque(false);
    }

    public void splashParameters() throws InterruptedException
    {
        for (int i = 0; i <= 200; i++)
        {
            Thread.sleep(40);
            progress.setForeground(Color.GREEN);
            progress.setValue(i);
            Connect cn = new Connect();
            
            if (i == 10)
            {
                state.setText("Conectando con base de datos.");
            }
            
            if (i == 20)
            {
                state.setText("Conectando con base de datos..");
            }
            
            if (i == 30)
            {
                state.setText("Conectando con base de datos...");
            }
            
            if (i == 40)
            {
                state.setText("Conectando con base de datos");
            }
            
            if (i == 50)
            {
                state.setText("Conectando con base de datos.");
            }
            
            if (i == 60)
            {
                state.setText("Conectando con base de datos..");
            }
            
            if (i == 70)
            {
                state.setText("Conectando con base de datos...");
            }
            
            if (i == 80)
            {
                if (String.valueOf(cn.connect()).contains("net.ucanaccess"))
                {
                    state.setText("Base de datos conectada");
                }
                else
                {
                    state.setText("Error: Base de datos no encontrada.");
                    Thread.sleep(3000);
                    System.exit(0);
                }
            }

            if (String.valueOf(cn.connect()).contains("net.ucanaccess") && i == 130)
            {
                state.setText("Listo");
            }
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents()
    {

        progress = new javax.swing.JProgressBar();
        state = new javax.swing.JLabel();

        state.setFont(new java.awt.Font("Kawak Light", 0, 16)); // NOI18N
        state.setText("Conectando con base de datos");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(progress, javax.swing.GroupLayout.DEFAULT_SIZE, 455, Short.MAX_VALUE)
            .addGroup(layout.createSequentialGroup()
                .addGap(17, 17, 17)
                .addComponent(state)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(0, 294, Short.MAX_VALUE)
                .addComponent(state)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(progress, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
        );
    }// </editor-fold>//GEN-END:initComponents
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JProgressBar progress;
    private javax.swing.JLabel state;
    // End of variables declaration//GEN-END:variables
}
